#!/bin/bash

./tools/build.sh
./tools/push.sh

# deploy by hook

export $(grep -v '^#' .env | xargs -d '\n')



if [ "$1" == "prod" ]; then
    echo "Deploying PRODUCTION Server via Deploy Hook $DEPLOY_HOOK"
    curlRun="curl -s $DEPLOY_HOOK"
    eval $curlRun
    echo ""
fi

echo "Deploying DEVLOPMENT Server via Deploy Hook $DEPLOY_HOOK_DEV"
curlRun="curl -s $DEPLOY_HOOK_DEV"
eval $curlRun
echo ""

echo "Done!"
